//! Turn the vendored WIT directory into something the crate can carry.
//!
//! The files are embedded rather than read from disk at run time. A path baked
//! in at compile time works right up until somebody clears the cargo registry
//! cache or vendors their dependencies, and then a plugin fails to build with
//! an error about a directory nobody has heard of. Bytes in the binary have no
//! such failure mode.
//!
//! Generated by walking the directory rather than listed by hand, so that
//! adding an interface to the world is one file and no bookkeeping.

use std::fmt::Write as _;

fn main() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("wit");
    println!("cargo:rerun-if-changed={}", root.display());

    let mut names: Vec<String> = std::fs::read_dir(&root)
        .expect("the vendored wit directory")
        .flatten()
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .filter(|name| name.ends_with(".wit"))
        .collect();
    // Sorted, so the generated file does not churn with directory order and
    // produce a different artifact on every machine.
    names.sort();

    assert!(!names.is_empty(), "no .wit files in {}", root.display());

    let mut out = String::from(
        "/// Every file of the `ferrum:plugin` world, as `(name, contents)`.\n\
         pub(crate) const WORLD: &[(&str, &str)] = &[\n",
    );
    for name in &names {
        // `concat!` against the manifest directory rather than an interpolated
        // absolute path: a Windows path inside a string literal needs its
        // separators escaped, and getting that wrong is a compile error in
        // generated code that nobody ever reads.
        let _ = writeln!(
            out,
            "    ({name:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/wit/\", {name:?}))),"
        );
    }
    out.push_str("];\n");

    let dest = std::path::Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("world.rs");
    std::fs::write(dest, out).expect("write the generated world list");
}
